<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace myapi\Models\Operations;

use \myapi\Utils\SpeakeasyMetadata;
class CreateApiProductVersionSpecRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \myapi\Models\Shared\CreateAPIProductVersionSpecDTO $createAPIProductVersionSpecDTO;
    
    /**
     * The API product identifier
     * 
     * @var string $apiProductId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=apiProductId')]
    public string $apiProductId;
    
    /**
     * The API product version identifier
     * 
     * @var string $productVersionId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=productVersionId')]
    public string $productVersionId;
    
	public function __construct()
	{
		$this->createAPIProductVersionSpecDTO = new \myapi\Models\Shared\CreateAPIProductVersionSpecDTO();
		$this->apiProductId = "";
		$this->productVersionId = "";
	}
}
