<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test_workspace-2\Konnect-API\Models\Operations;


/**
 * CreateApiProductDocument409ApplicationProblemPlusJson - Conflict - `slug` property must be unique
 * 
 * @package test_workspace-2\Konnect-API\Models\Operations
 * @access public
 */
class CreateApiProductDocument409ApplicationProblemPlusJson
{
	#[\JMS\Serializer\Annotation\SerializedName('instance')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $instance;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $status;
    
	#[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $title;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $type = null;
    
	public function __construct()
	{
		$this->instance = "";
		$this->status = 0;
		$this->title = "";
		$this->type = null;
	}
}
