<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace myapi\Models\Operations;

use \myapi\Utils\SpeakeasyMetadata;
class CreateApiProductDocumentRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \myapi\Models\Shared\CreateAPIProductDocumentDTO $createAPIProductDocumentDTO;
    
    /**
     * The API product identifier
     * 
     * @var string $apiProductId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=apiProductId')]
    public string $apiProductId;
    
	public function __construct()
	{
		$this->createAPIProductDocumentDTO = new \myapi\Models\Shared\CreateAPIProductDocumentDTO();
		$this->apiProductId = "";
	}
}
