<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test_workspace-2\Konnect-API\Models\Operations;


/**
 * GetManyApiProductDocument200ApplicationJSON - List of API product documents
 * 
 * @package test_workspace-2\Konnect-API\Models\Operations
 * @access public
 */
class GetManyApiProductDocument200ApplicationJSON
{
    /**
     * $data
     * 
     * @var array<\test_workspace-2\Konnect-API\Models\Shared\APIProductDocumentSummary> $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<test_workspace-2\Konnect-API\Models\Shared\APIProductDocumentSummary>')]
    public array $data;
    
    /**
     * returns the pagination information
     * 
     * @var \test_workspace-2\Konnect-API\Models\Shared\PaginatedMeta $meta
     */
	#[\JMS\Serializer\Annotation\SerializedName('meta')]
    #[\JMS\Serializer\Annotation\Type('test_workspace-2\Konnect-API\Models\Shared\PaginatedMeta')]
    public \test_workspace-2\Konnect-API\Models\Shared\PaginatedMeta $meta;
    
	public function __construct()
	{
		$this->data = [];
		$this->meta = new \test_workspace-2\Konnect-API\Models\Shared\PaginatedMeta();
	}
}
