<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace myapi\Models\Operations;

use \myapi\Utils\SpeakeasyMetadata;
class UpdateApiProductDocumentRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \myapi\Models\Shared\UpdateAPIProductDocumentDTO $updateAPIProductDocumentDTO;
    
    /**
     * The API product identifier
     * 
     * @var string $apiProductId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=apiProductId')]
    public string $apiProductId;
    
    /**
     * The document identifier related to the API product
     * 
     * @var string $id
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;
    
	public function __construct()
	{
		$this->updateAPIProductDocumentDTO = new \myapi\Models\Shared\UpdateAPIProductDocumentDTO();
		$this->apiProductId = "";
		$this->id = "";
	}
}
