<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace myapi\Models\Operations;


class UpdateApiProductDocumentResponse
{
    /**
     * API product document
     * 
     * @var ?\myapi\Models\Shared\APIProductDocument $apiProductDocument
     */
	
    public ?\myapi\Models\Shared\APIProductDocument $apiProductDocument = null;
    
    /**
     * Bad Request
     * 
     * @var ?\myapi\Models\Shared\BadRequestError $badRequestError
     */
	
    public ?\myapi\Models\Shared\BadRequestError $badRequestError = null;
    
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * Forbidden
     * 
     * @var ?\myapi\Models\Shared\ForbiddenError $forbiddenError
     */
	
    public ?\myapi\Models\Shared\ForbiddenError $forbiddenError = null;
    
    /**
     * Not Found
     * 
     * @var ?\myapi\Models\Shared\NotFoundError $notFoundError
     */
	
    public ?\myapi\Models\Shared\NotFoundError $notFoundError = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Unauthorized
     * 
     * @var ?\myapi\Models\Shared\UnauthorizedError $unauthorizedError
     */
	
    public ?\myapi\Models\Shared\UnauthorizedError $unauthorizedError = null;
    
    /**
     * Unsupported Media Type
     * 
     * @var ?\myapi\Models\Shared\UnsupportedMediaTypeError $unsupportedMediaTypeError
     */
	
    public ?\myapi\Models\Shared\UnsupportedMediaTypeError $unsupportedMediaTypeError = null;
    
    /**
     * Conflict - `slug` property must be unique
     * 
     * @var ?\myapi\Models\Operations\UpdateApiProductDocument409ApplicationProblemPlusJson $updateApiProductDocument409ApplicationProblemPlusJsonObject
     */
	
    public ?UpdateApiProductDocument409ApplicationProblemPlusJson $updateApiProductDocument409ApplicationProblemPlusJsonObject = null;
    
	public function __construct()
	{
		$this->apiProductDocument = null;
		$this->badRequestError = null;
		$this->contentType = "";
		$this->forbiddenError = null;
		$this->notFoundError = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->unauthorizedError = null;
		$this->unsupportedMediaTypeError = null;
		$this->updateApiProductDocument409ApplicationProblemPlusJsonObject = null;
	}
}
