<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace myapi\Models\Operations;

use \myapi\Utils\SpeakeasyMetadata;
class UpdateApiProductRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \myapi\Models\Shared\UpdateAPIProductDTO $updateAPIProductDTO;
    
    /**
     * API product identifier
     * 
     * @var string $id
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;
    
	public function __construct()
	{
		$this->updateAPIProductDTO = new \myapi\Models\Shared\UpdateAPIProductDTO();
		$this->id = "";
	}
}
