<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test_workspace-2\Konnect-API\Models\Shared;


/**
 * APIProductDocument - an api product document
 * 
 * @package test_workspace-2\Konnect-API\Models\Shared
 * @access public
 */
class APIProductDocument
{
    /**
     * $ast
     * 
     * @var array<mixed> $ast
     */
	#[\JMS\Serializer\Annotation\SerializedName('ast')]
    #[\JMS\Serializer\Annotation\Type('array<mixed>')]
    public array $ast;
    
    /**
     * An ISO-8601 timestamp representation of entity creation date.
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('test_workspace-2\Konnect-API\Models\Shared\APIProductDocumentMetadata')]
    public APIProductDocumentMetadata $metadata;
    
	#[\JMS\Serializer\Annotation\SerializedName('parent_document_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $parentDocumentId;
    
	#[\JMS\Serializer\Annotation\SerializedName('slug')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $slug;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<test_workspace-2\Konnect-API\Models\Shared\APIProductDocumentStatus>')]
    public APIProductDocumentStatus $status;
    
	#[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $title;
    
    /**
     * An ISO-8601 timestamp representation of entity update date.
     * 
     * @var \DateTime $updatedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $updatedAt;
    
	public function __construct()
	{
		$this->ast = [];
		$this->createdAt = new \DateTime();
		$this->id = "";
		$this->metadata = new \test_workspace-2\Konnect-API\Models\Shared\APIProductDocumentMetadata();
		$this->parentDocumentId = "";
		$this->slug = "";
		$this->status = \test_workspace-2\Konnect-API\Models\Shared\APIProductDocumentStatus::Unpublished;
		$this->title = "";
		$this->updatedAt = new \DateTime();
	}
}
