<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test_workspace-2\Konnect-API\Models\Shared;


/** The publish status of the API product version */
enum APIProductVersionPublishStatus: string
{
    case Unpublished = 'unpublished';
    case Published = 'published';
}
