<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test_workspace-2\Konnect-API\Models\Shared;

use \test_workspace-2\Konnect-API\Utils\SpeakeasyMetadata;
class APIProductVersionFilterParameters
{
    /**
     * Filter a string value field either by exact match or partial contains.
     * 
     * @var mixed $name
     */
	#[SpeakeasyMetadata('queryParam:name=name')]
    public mixed $name = null;
    
	public function __construct()
	{
		$this->name = null;
	}
}
