<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test_workspace-2\Konnect-API\Models\Shared;


class APIProductVersionGatewayService
{
    /**
     * The identifier of the control plane that the gateway service resides in
     * 
     * @var string $controlPlaneId
     */
	#[\JMS\Serializer\Annotation\SerializedName('control_plane_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $controlPlaneId;
    
    /**
     * The identifier of a gateway service associated with the version of the API product.
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * This field is deprecated, please use `control_plane_id` instead. The identifier of the control plane that the gateway service resides in
     * 
     * @var string $runtimeGroupId
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
	#[\JMS\Serializer\Annotation\SerializedName('runtime_group_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $runtimeGroupId;
    
	public function __construct()
	{
		$this->controlPlaneId = "";
		$this->id = "";
		$this->runtimeGroupId = "";
	}
}
