<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test_workspace-2\Konnect-API\Models\Shared;


/**
 * CreateAPIProductDocumentDTO - a document payload
 * 
 * @package test_workspace-2\Konnect-API\Models\Shared
 * @access public
 */
class CreateAPIProductDocumentDTO
{
    /**
     * Must be a base64 encoded string
     * 
     * @var string $content
     */
	#[\JMS\Serializer\Annotation\SerializedName('content')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $content;
    
    /**
     * metadata of the document
     * 
     * @var ?\test_workspace-2\Konnect-API\Models\Shared\CreateAPIProductDocumentDTOMetadata $metadata
     */
	#[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('test_workspace-2\Konnect-API\Models\Shared\CreateAPIProductDocumentDTOMetadata')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreateAPIProductDocumentDTOMetadata $metadata = null;
    
    /**
     * parent document id
     * 
     * @var ?string $parentDocumentId
     */
	#[\JMS\Serializer\Annotation\SerializedName('parent_document_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $parentDocumentId = null;
    
    /**
     * document slug. must be unique accross documents belonging to an api product
     * 
     * @var string $slug
     */
	#[\JMS\Serializer\Annotation\SerializedName('slug')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $slug;
    
    /**
     * document publish status
     * 
     * @var \test_workspace-2\Konnect-API\Models\Shared\PublishStatus $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<test_workspace-2\Konnect-API\Models\Shared\PublishStatus>')]
    public PublishStatus $status;
    
    /**
     * document title
     * 
     * @var string $title
     */
	#[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $title;
    
	public function __construct()
	{
		$this->content = "";
		$this->metadata = null;
		$this->parentDocumentId = null;
		$this->slug = "";
		$this->status = \test_workspace-2\Konnect-API\Models\Shared\PublishStatus::Published;
		$this->title = "";
	}
}
