<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace myapi\Models\Shared;


/**
 * CreateAPIProductVersionDTO - The request schema to create a version of an API product.
 * 
 * @package myapi\Models\Shared
 * @access public
 */
class CreateAPIProductVersionDTO
{
    /**
     * Indicates if the version of the API product is deprecated.
     * 
     * @var ?bool $deprecated
     */
	#[\JMS\Serializer\Annotation\SerializedName('deprecated')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $deprecated = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('gateway_service')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public mixed $gatewayService = null;
    
    /**
     * The version name of the API product version.
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The publish status of the API product version.
     * 
     * @var ?\myapi\Models\Shared\CreateAPIProductVersionDTOPublishStatus $publishStatus
     */
	#[\JMS\Serializer\Annotation\SerializedName('publish_status')]
    #[\JMS\Serializer\Annotation\Type('enum<myapi\Models\Shared\CreateAPIProductVersionDTOPublishStatus>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreateAPIProductVersionDTOPublishStatus $publishStatus = null;
    
	public function __construct()
	{
		$this->deprecated = null;
		$this->gatewayService = null;
		$this->name = "";
		$this->publishStatus = null;
	}
}
