<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace myapi\Models\Shared;


/**
 * DocumentTreeMetadata - metadata of the document
 * 
 * @package myapi\Models\Shared
 * @access public
 */
class DocumentTreeMetadata
{
	public function __construct()
	{
	}
}
