<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test_workspace-2\Konnect-API\Models\Shared;


/**
 * DocumentTreeMetadata - metadata of the document
 * 
 * @package test_workspace-2\Konnect-API\Models\Shared
 * @access public
 */
class DocumentTreeMetadata
{
	public function __construct()
	{
	}
}
