<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test_workspace-2\Konnect-API\Models\Shared;


class InvalidParameterChoiceItem
{
    /**
     * $choices
     * 
     * @var ?array<mixed> $choices
     */
	#[\JMS\Serializer\Annotation\SerializedName('choices')]
    #[\JMS\Serializer\Annotation\Type('array<mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $choices = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('field')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $field;
    
	#[\JMS\Serializer\Annotation\SerializedName('reason')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $reason;
    
    /**
     * invalid parameters rules
     * 
     * @var ?\test_workspace-2\Konnect-API\Models\Shared\InvalidRules $rule
     */
	#[\JMS\Serializer\Annotation\SerializedName('rule')]
    #[\JMS\Serializer\Annotation\Type('enum<test_workspace-2\Konnect-API\Models\Shared\InvalidRules>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?InvalidRules $rule = null;
    
	public function __construct()
	{
		$this->choices = null;
		$this->field = "";
		$this->reason = "";
		$this->rule = null;
	}
}
