<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test_workspace-2\Konnect-API\Models\Shared;


/** invalid parameters rules */
enum InvalidRules: string
{
    case Required = 'required';
    case Enum = 'enum';
    case MinLength = 'min_length';
    case MaxLength = 'max_length';
    case MinDigits = 'min_digits';
    case MinLowercase = 'min_lowercase';
    case MinUppercase = 'min_uppercase';
    case MinSymbols = 'min_symbols';
    case IsArray = 'is_array';
    case IsBase64 = 'is_base64';
    case IsBoolean = 'is_boolean';
    case IsDateTime = 'is_date_time';
    case IsInteger = 'is_integer';
    case IsNull = 'is_null';
    case IsNumber = 'is_number';
    case IsObject = 'is_object';
    case IsString = 'is_string';
    case IsUuid = 'is_uuid';
    case UnknownProperty = 'unknown_property';
    case IsLabel = 'is_label';
    case MatchesRegex = 'matches_regex';
}
