<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace myapi\Models\Shared;


/**
 * PageMeta - Contains pagination query parameters and the total number of objects returned.
 * 
 * @package myapi\Models\Shared
 * @access public
 */
class PageMeta
{
	#[\JMS\Serializer\Annotation\SerializedName('number')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $number;
    
	#[\JMS\Serializer\Annotation\SerializedName('size')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $size;
    
	#[\JMS\Serializer\Annotation\SerializedName('total')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $total;
    
	public function __construct()
	{
		$this->number = 0;
		$this->size = 0;
		$this->total = 0;
	}
}
