<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace myapi\Models\Shared;


/**
 * PaginatedMeta - returns the pagination information
 * 
 * @package myapi\Models\Shared
 * @access public
 */
class PaginatedMeta
{
    /**
     * Contains pagination query parameters and the total number of objects returned.
     * 
     * @var \myapi\Models\Shared\PageMeta $page
     */
	#[\JMS\Serializer\Annotation\SerializedName('page')]
    #[\JMS\Serializer\Annotation\Type('myapi\Models\Shared\PageMeta')]
    public PageMeta $page;
    
	public function __construct()
	{
		$this->page = new \myapi\Models\Shared\PageMeta();
	}
}
