<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace myapi\Models\Shared;


/** document publish status */
enum PublishStatus: string
{
    case Published = 'published';
    case Unpublished = 'unpublished';
}
