<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test_workspace-2\Konnect-API\Models\Shared;

use \test_workspace-2\Konnect-API\Utils\SpeakeasyMetadata;
class Security
{
	#[SpeakeasyMetadata('security:scheme=true,type=http,subtype=bearer,name=Authorization')]
    public ?string $personalAccessToken = null;
    
	#[SpeakeasyMetadata('security:scheme=true,type=http,subtype=bearer,name=Authorization')]
    public ?string $systemAccountAccessToken = null;
    
	public function __construct()
	{
		$this->personalAccessToken = null;
		$this->systemAccountAccessToken = null;
	}
}
