<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test_workspace-2\Konnect-API\Models\Shared;


/**
 * UpdateAPIProductVersionDTO - The request schema for updating a version of an API product.
 * 
 * @package test_workspace-2\Konnect-API\Models\Shared
 * @access public
 */
class UpdateAPIProductVersionDTO
{
    /**
     * Indicates if the version of the API product is deprecated.
     * 
     * @var ?bool $deprecated
     */
	#[\JMS\Serializer\Annotation\SerializedName('deprecated')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $deprecated = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('gateway_service')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public mixed $gatewayService = null;
    
    /**
     * The version name of the API product version.
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
    /**
     * When set to `true`, and all the following conditions are true:
     * 
     * - version of the API product deprecation has changed from `false` -> `true`
     * - version of the API product is published
     * 
     * then consumers of the now deprecated verion of the API product will be notified.
     * 
     * 
     * @var ?bool $notify
     */
	#[\JMS\Serializer\Annotation\SerializedName('notify')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $notify = null;
    
    /**
     * The publish status of the API product version.
     * 
     * @var ?\test_workspace-2\Konnect-API\Models\Shared\UpdateAPIProductVersionDTOPublishStatus $publishStatus
     */
	#[\JMS\Serializer\Annotation\SerializedName('publish_status')]
    #[\JMS\Serializer\Annotation\Type('enum<test_workspace-2\Konnect-API\Models\Shared\UpdateAPIProductVersionDTOPublishStatus>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?UpdateAPIProductVersionDTOPublishStatus $publishStatus = null;
    
	public function __construct()
	{
		$this->deprecated = null;
		$this->gatewayService = null;
		$this->name = null;
		$this->notify = null;
		$this->publishStatus = null;
	}
}
