<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace myapi\Models\Shared;


/** The publish status of the API product version. */
enum UpdateAPIProductVersionDTOPublishStatus: string
{
    case Unpublished = 'unpublished';
    case Published = 'published';
}
