<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace myapi\Models\Shared;


class UpdateAPIProductDocumentDTOMetadata
{
	public function __construct()
	{
	}
}
