<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace test_workspace-2\Konnect-API;

class SDKConfiguration
{
	public ?\GuzzleHttp\ClientInterface $defaultClient = null;
	public ?\GuzzleHttp\ClientInterface $securityClient = null;
	public ?Models\Shared\Security $security = null;
	public string $serverUrl = '';
	public int $serverIndex = 0;
	public string $language = 'php';
	public string $openapiDocVersion = '2.0.0';
	public string $sdkVersion = '0.1.0';
	public string $genVersion = '2.159.1';
	public string $userAgent = 'speakeasy-sdk/php 0.1.0 2.159.1 2.0.0 test-workspace-2/konnect-api';
	

	public function getServerUrl(): string
	{
		
		if ($this->serverUrl !== '') {
			return $this->serverUrl;
		};
		return KonnectAPI::SERVERS[$this->serverIndex];
	}
	
}